package com.balancenotifier.telegram.handler;

public enum UserStatus {
	
	HAS_NO_PROFILES,
	HAS_NO_ADDRESS,
	ADD_NEW_PROFILE,
	ADD_NEW_ADDRESS,
	WAITING_FOR_PROFILE_NAME,
	WAITING_FOR_WALLET_NAME,
	WAITING_FOR_API,
	WAITING_FOR_SECRET,
	WAITING_FOR_ADDRESS_ALIAS,
	WAITING_FOR_WALLET_ADDRESS,
	ACTIVE
	
}
